#Telepresence Travis CI Build Script

#Disable email notifications
notifications:
    email: false

#Use Ubuntu 14.04 LTS build environment
os: linux
sudo: required
dist: trusty

#Language and compiler settings
language: cpp
compiler: g++

#Environment matrix
env:
    - OS=""
    - OS="Windows_NT"

#Install dependencies
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libjsoncpp-dev
    - sudo apt-get install -qq g++-mingw-w64-i686

#Build Telepresence
script:
    - make
